# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3.0.0
    # if not fetch all history, all files will have the same timestamp!
      with:
        fetch-depth: 0
    # change timezone Asia/Shanghai
    - run: sudo timedatectl set-timezone Asia/Shanghai
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run docs:build
    
    - name: Deploy to Server
      uses: buxianshan/fine-sftp-deployer@v0.1.5
      with:
        # username
        username: ${{secrets.SERVER_USERNAME}}
        # your server ip or domain
        server: ${{secrets.SERVER_DOMAIN}}
        # your server ssh port, the default is 22
        port: ${{secrets.SERVER_PORT}}
        # ssh private key
        ssh_private_key: ${{secrets.SERVER_KEY_PEM}}
        # local dist file path
        local_path: ./dist/*
        # dist file path on your server
        remote_path: ${{secrets.SERVER_WORKSPACE}}
        # delete all files in remote_path(default is false)
        clear_remote_path: true
