# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
#     types:
#       - closed
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3.0.0
    # if not fetch all history, all files will have the same timestamp!
      with:
        fetch-depth: 0
    # change timezone Asia/Shanghai
    - run: sudo timedatectl set-timezone Asia/Shanghai
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run docs:build
    
    # build docker image
    - name: Login to Docker Hub
      run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/bxs-blog:latest
    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bxs-blog:latest
        
    # 把base修改为/bxs-blog/，然后再build
    - run: sed -i 's#base:\ "/"#base:\ "/bxs-blog/"#g' ./docs/.vuepress/config.js
    - run: npm run docs:build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
